alias gti='git'
alias gst='git status'
alias gsw='git switch'
alias gswc='git switch -C'
alias gup='git fetch --all --prune && git rebase --autostash'
alias gsu='git submodule update'
alias gsui='git submodule update --init'
alias gp='git push'
alias gsta='git stash'
alias gstp='git stash pop'
alias gaa='git add .'
alias gc='git commit'
alias gba='git branch --all'
alias gsn='git show --name-only'
alias gstu='git stash --include-untracked'
alias gfa='git fetch --all --prune'
alias shortlog='git shortlog -sn --all --no-merges --since="1 year ago"'

alias e='exec zsh'
alias l='ls -la'
alias config='${EDITOR:-nvim} "$ZDOTDIR/.zshrc"'
alias startPy='python3 -m venv .venv && source .venv/bin/activate'

(( $+commands[opencode] )) && alias oc='opencode'
(( $+commands[atuin] )) && alias asr='atuin scripts run'
